default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: gigster_expense_tracker

test:
  <<: *default
  database: gigster_expense_tracker_test

production:
  <<: *default
  database: gigster_expense_tracker
